import argparse
import json
import sys
from pathlib import Path

import torch

try:
    from jit_diffusers import JiTTransformer2DModel
except ModuleNotFoundError:
    sys.path.append(str(Path(__file__).resolve().parents[1]))
    from jit_diffusers import JiTTransformer2DModel


def get_args():
    parser = argparse.ArgumentParser(description="Convert diffusers JiT model back to JiT checkpoint format.")
    parser.add_argument("--model_path", type=str, required=True, help="Path to diffusers model directory.")
    parser.add_argument("--output_path", type=str, required=True, help="Output JiT checkpoint path (.pth).")
    parser.add_argument(
        "--ema_mode",
        type=str,
        default="copy_to_both",
        choices=["none", "copy_to_both"],
        help="How to reconstruct EMA states in JiT checkpoint.",
    )
    parser.add_argument(
        "--epoch",
        type=int,
        default=0,
        help="Epoch value to store in the output checkpoint.",
    )
    parser.add_argument(
        "--metadata_path",
        type=str,
        default=None,
        help="Optional conversion_metadata.json generated by convert_jit_to_diffusers.py.",
    )
    return parser.parse_args()


def _first_present(mapping, *keys):
    for key in keys:
        if key in mapping and mapping[key] is not None:
            return mapping[key]
    return None


def _config_first(config, *keys, default=None, required: bool = False):
    for key in keys:
        value = getattr(config, key, None)
        if value is not None:
            return value
    if required:
        raise ValueError(f"Missing required config fields: {keys}")
    return default


def main():
    args = get_args()

    model = JiTTransformer2DModel.from_pretrained(args.model_path)
    checkpoint = model.to_jit_checkpoint(ema_mode=args.ema_mode)
    checkpoint["epoch"] = args.epoch
    checkpoint["optimizer"] = {}

    model_path = Path(args.model_path)
    metadata_path = Path(args.metadata_path) if args.metadata_path else model_path / "conversion_metadata.json"
    metadata_args = None
    if metadata_path.exists():
        with metadata_path.open("r", encoding="utf-8") as file:
            metadata = json.load(file)
        metadata_args = metadata.get("jit_args")

    source_args = metadata_args or {}

    model_type = _first_present(source_args, "model_type", "model_name", "model")
    if model_type is None:
        model_type = _config_first(model.config, "model_type", "model_name", required=True)

    sample_size = _first_present(source_args, "sample_size", "image_size", "img_size")
    if sample_size is None:
        sample_size = _config_first(model.config, "sample_size", "image_size", required=True)

    num_class_embeds = _first_present(source_args, "num_class_embeds", "num_classes", "class_num")
    if num_class_embeds is None:
        num_class_embeds = _config_first(model.config, "num_class_embeds", "num_classes", required=True)

    attention_dropout = _first_present(source_args, "attention_dropout", "attn_dropout")
    if attention_dropout is None:
        attention_dropout = _config_first(model.config, "attention_dropout", "attn_dropout", default=0.0)

    dropout = _first_present(source_args, "dropout", "proj_dropout")
    if dropout is None:
        dropout = _config_first(model.config, "dropout", "proj_dropout", default=0.0)

    args_dict = {
        "model": model_type,
        "img_size": sample_size,
        "class_num": num_class_embeds,
        "attn_dropout": attention_dropout,
        "proj_dropout": dropout,
        # Keep diffusers-style aliases alongside legacy JiT keys for compatibility.
        "model_type": model_type,
        "sample_size": sample_size,
        "num_class_embeds": num_class_embeds,
        "attention_dropout": attention_dropout,
        "dropout": dropout,
    }
    checkpoint["args"] = argparse.Namespace(**args_dict)

    output_path = Path(args.output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(checkpoint, output_path)
    print(f"Saved JiT checkpoint to: {output_path}")


if __name__ == "__main__":
    main()
