import argparse
import json
import os

import torch

from jit_diffusers import JiTDiffusersModel


def get_args():
    parser = argparse.ArgumentParser(description="Convert diffusers JiT model back to JiT checkpoint format.")
    parser.add_argument("--model_path", type=str, required=True, help="Path to diffusers model directory.")
    parser.add_argument("--output_path", type=str, required=True, help="Output JiT checkpoint path (.pth).")
    parser.add_argument(
        "--ema_mode",
        type=str,
        default="copy_to_both",
        choices=["none", "copy_to_both"],
        help="How to reconstruct EMA states in JiT checkpoint.",
    )
    parser.add_argument(
        "--epoch",
        type=int,
        default=0,
        help="Epoch value to store in the output checkpoint.",
    )
    parser.add_argument(
        "--metadata_path",
        type=str,
        default=None,
        help="Optional conversion_metadata.json generated by convert_jit_to_diffusers.py.",
    )
    return parser.parse_args()


def main():
    args = get_args()

    model = JiTDiffusersModel.from_pretrained(args.model_path)
    checkpoint = model.to_jit_checkpoint(ema_mode=args.ema_mode)
    checkpoint["epoch"] = args.epoch
    checkpoint["optimizer"] = {}

    metadata_path = args.metadata_path or os.path.join(args.model_path, "conversion_metadata.json")
    metadata_args = None
    if os.path.exists(metadata_path):
        with open(metadata_path, "r", encoding="utf-8") as f:
            metadata = json.load(f)
        metadata_args = metadata.get("jit_args")

    args_dict = metadata_args or {
        "model": model.config.model_name,
        "img_size": model.config.image_size,
        "class_num": model.config.num_classes,
        "attn_dropout": model.config.attn_dropout,
        "proj_dropout": model.config.proj_dropout,
    }
    checkpoint["args"] = argparse.Namespace(**args_dict)

    output_dir = os.path.dirname(os.path.abspath(args.output_path))
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    torch.save(checkpoint, args.output_path)
    print(f"Saved JiT checkpoint to: {args.output_path}")


if __name__ == "__main__":
    main()
